export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const CURRENT_USER_PROFILE_DETAILS_REQUEST =
  "CURRENT_USER_PROFILE_DETAILS_REQUEST";
export const CURRENT_USER_PROFILE_DETAILS_SUCCESS =
  "CURRENT_USER_PROFILE_DETAILS_SUCCESS";
export const CURRENT_USER_PROFILE_DETAILS_FAIL =
  "CURRENT_USER_PROFILE_DETAILS_FAIL";

export const AUTHENTICATE = "AUTHENTICATE";
export const DEAUTHENTICATE = "DEAUTHENTICATE";
