export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_DETAILS = "USER_REGISTER_DETAILS";
export const USER_LOGIN_DETAILS = "USER_LOGIN_DETAILS";
export const CURRENT_USER_PROFILE_DETAILS =
  "CURRENT_USER_PROFILE_DETAILS";
export const USER_LOADING_ACTION = "USER_LOADING_ACTION";
export const AUTHENTICATE = "AUTHENTICATE";
export const DEAUTHENTICATE = "DEAUTHENTICATE";
