export const POST_LIST_NEWS_FEED_REQUEST =
  "POST_LIST_NEWS_FEED_REQUEST";
export const POST_LIST_NEWS_FEED_SUCCESS =
  "POST_LIST_NEWS_FEED_SUCCESS";
export const POST_LIST_NEWS_FEED_FAIL = "POST_LIST_NEWS_FEED_FAIL";
export const UPDATE_POST_LIST = "UPDATE_POST_LIST";

export const POST_LIST_BY_USER_REQUEST = "POST_LIST_BY_USER_REQUEST";
export const POST_LIST_BY_USER_SUCCESS = "POST_LIST_BY_USER_SUCCESS";
export const POST_LIST_BY_USER_FAIL = "POST_LIST_BY_USER_FAIL";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";

export const POST_REMOVE_REQUEST = "POST_REMOVE_REQUEST";
export const POST_REMOVE_SUCCESS = "POST_REMOVE_SUCCESS";
export const POST_REMOVE_FAIL = "POST_REMOVE_FAIL";
